# Generated by Django 5.2.8 on 2025-11-21 16:28

import apps.qa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='نام')),
                ('help_image', models.ImageField(blank=True, null=True, upload_to=apps.qa.models.upload_to_question, verbose_name='تصویر کمکی')),
                ('question_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سوال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('solved', models.BooleanField(default=False, verbose_name='حل شده')),
                ('is_pin', models.BooleanField(default=False, verbose_name='ویژه')),
                ('write_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ مطرح شدن')),
                ('solve_date', models.DateTimeField(verbose_name='تاریخ حل شدن')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
            },
        ),
    ]
