# Generated by Django 5.2.8 on 2025-11-21 16:37

import apps.qa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=110, verbose_name='نام')),
                ('answer_description', models.TextField(blank=True, null=True, verbose_name='توضیحات پاسخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_best', models.BooleanField(default=False, verbose_name='بهترین')),
                ('write_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ مطرح شدن')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=110, verbose_name='نام'),
        ),
    ]
