# Generated by Django 5.2.8 on 2025-12-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_answer_alter_question_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='solve_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حل شدن'),
        ),
    ]
