# Generated by Django 5.2.8 on 2025-12-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_answer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='test', unique=True, verbose_name='شناسه'),
            preserve_default=False,
        ),
    ]
