# Generated by Django 5.2.8 on 2025-12-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0009_remove_answer_name_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dis_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='دیسلایک ها'),
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='لایک ها'),
        ),
        migrations.AddField(
            model_name='question',
            name='dis_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='دیسلایک ها'),
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='لایک ها'),
        ),
    ]
