# Generated by Django 5.2.8 on 2025-12-06 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0012_remove_answer_dis_likes_remove_answer_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adislike',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='qa.answer'),
        ),
        migrations.AlterField(
            model_name='alike',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='qa.answer'),
        ),
        migrations.AlterField(
            model_name='qdislike',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='qa.question'),
        ),
        migrations.AlterField(
            model_name='qlike',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='qa.question'),
        ),
    ]
