# Generated by Django 5.2.8 on 2025-12-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0014_questioncategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncategory',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(to='qa.questioncategory'),
        ),
    ]
