# Generated by Django 5.2.8 on 2025-12-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category'),
        ('qa', '0016_delete_questioncategory_alter_question_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(related_name='questions', to='core.category', verbose_name='دسته\u200cبندی\u200cها'),
        ),
    ]
