# Generated by Django 5.2.8 on 2025-11-24 07:07

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='درباره کاربر'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.CustomUser.avatar_upload_path, verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='x', verbose_name='شناسه کاربری'),
            preserve_default=False,
        ),
    ]
