# Generated by Django 5.2.8 on 2025-11-27 08:46

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='git_account',
            field=models.URLField(blank=True, null=True, validators=[apps.accounts.validators.validate_git_url], verbose_name='حساب گیت هاب/گیت لب'),
        ),
    ]
