# Generated by Django 5.2.8 on 2025-11-27 10:31

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_git_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(blank=True, null=True, validators=[apps.accounts.validators.validate_facebook_link], verbose_name='فیس بوک'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.URLField(blank=True, null=True, validators=[apps.accounts.validators.validate_instagram_link], verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(blank=True, null=True, validators=[apps.accounts.validators.validate_linkedin_link], verbose_name='لینکدین'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram',
            field=models.URLField(blank=True, null=True, validators=[apps.accounts.validators.validate_telegram_link], verbose_name='تلگرام'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='سایت کاربر'),
        ),
    ]
