# Generated by Django 5.2.8 on 2025-11-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_public_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='public_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل عمومی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='public_phone_number',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='شماره تلفن عمومی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='سایت'),
        ),
    ]
