# Generated by Django 5.2.8 on 2025-11-30 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_public_email_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(verbose_name='نام لینک')),
                ('link_url', models.URLField(verbose_name='مکان لینک')),
                ('link_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.linkmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BaseLink',
                'verbose_name_plural': 'BaseLinks',
                'abstract': False,
            },
        ),
    ]
