# Generated by Django 5.2.8 on 2025-12-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profilelink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilelink',
            options={'verbose_name': 'لینک', 'verbose_name_plural': 'لینک ها'},
        ),
    ]
