# Generated by Django 5.2.8 on 2025-12-04 05:03

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profilelink_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='media/auth/avatars/20251204/person.png', upload_to=apps.accounts.models.CustomUser.avatar_upload_path, verbose_name='avatar'),
        ),
    ]
