# Generated by Django 5.2.8 on 2025-11-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimodel',
            name='revoked_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بازیابی'),
        ),
    ]
