# Generated by Django 5.2.8 on 2025-12-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apimodel_revoked_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apimodel',
            name='نام رابط',
        ),
        migrations.AddField(
            model_name='apimodel',
            name='api_name',
            field=models.CharField(default='test', max_length=110, verbose_name='نام رابط'),
            preserve_default=False,
        ),
    ]
