# Generated by Django 5.2.8 on 2025-11-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_facebook_customuser_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='public_article',
            field=models.BooleanField(default=False, help_text='با این گزینه،پست های شما عمومی محسوب شده و قابل استفاده توسط دیگران است', verbose_name='مقاله عمومی'),
        ),
    ]
