# Generated by Django 5.2.8 on 2025-12-04 14:20

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[apps.accounts.validators.validate_phone_number], verbose_name='شماره تلفن'),
        ),
    ]
