# Generated by Django 5.2.8 on 2025-12-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='slug',
            field=models.SlugField(default='test', unique=True, verbose_name='شناسه'),
            preserve_default=False,
        ),
    ]
