# Generated by Django 5.2.8 on 2025-12-02 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0006_question_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="qa.question"
            ),
            preserve_default=False,
        ),
    ]
