# Generated by Django 5.2.8 on 2025-12-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0010_answer_dis_likes_answer_likes_question_dis_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='slug',
        ),
    ]
