# Generated by Django 5.2.8 on 2025-12-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category'),
        ('qa', '0015_remove_questioncategory_question_question_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionCategory',
        ),
        migrations.AlterField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(to='core.category'),
        ),
    ]
