# Generated by Django 5.2.8 on 2025-11-27 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='نام')),
            ],
        ),
        migrations.CreateModel(
            name='BaseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(verbose_name='نام لینک')),
                ('link_url', models.URLField(verbose_name='مکان لینک')),
                ('link_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.linkmodel')),
            ],
            options={
                'verbose_name': 'BaseLink',
                'verbose_name_plural': 'BaseLinks',
            },
        ),
    ]
