# Generated by Django 5.2.8 on 2025-12-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='name',
            field=models.CharField(max_length=110, verbose_name='نام'),
        ),
    ]
