# Generated by Django 5.2.8 on 2025-12-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_linkmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkmodel',
            options={'verbose_name': 'نوع لینک', 'verbose_name_plural': 'انواع لینک'},
        ),
    ]
