# Generated by Django 5.2.8 on 2025-12-07 05:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
