# Generated by Django 5.2.8 on 2025-12-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug', verbose_name='شناسه'),
            preserve_default=False,
        ),
    ]
