# Generated by Django 5.2.8 on 2025-11-28 05:34

import apps.blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110, verbose_name='نام برچسب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیح برچسب')),
                ('slug', models.SlugField(verbose_name='شناسه')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='موضوع')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.blog.models.Article.thumbnail_upload_path, verbose_name='تصویر بندانگشتی')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
                ('short_description', models.CharField(max_length=110, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_verify', models.BooleanField(default=False, verbose_name='تائید شده')),
                ('is_pin', models.BooleanField(default=False, verbose_name='ویژه')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه')),
                ('write_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نوشتن')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('verify_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تائید')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('categories', models.ManyToManyField(to='blog.articlecategory')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
