# Generated by Django 5.2.8 on 2025-11-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='test', verbose_name='شناسه'),
            preserve_default=False,
        ),
    ]
