# Generated by Django 5.2.8 on 2025-11-28 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_options_alter_article_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.articlecomment'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='is_pin',
            field=models.BooleanField(default=False),
        ),
    ]
