# Generated by Django 5.2.8 on 2025-12-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_short_description'),
        ('core', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleCategory',
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='articles', to='core.category', verbose_name='دسته\u200cبندی\u200cها'),
        ),
    ]
