# Generated by Django 5.2.8 on 2025-11-28 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_articlecomment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.articlecomment'),
        ),
    ]
