# Generated by Django 5.2.8 on 2025-11-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_articlecomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
