# Generated by Django 5.2.8 on 2025-11-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_options_subscriptionplan_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='value',
            field=models.PositiveIntegerField(default=0, verbose_name='ارزش پلن'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_name',
            field=models.CharField(verbose_name='نام پلن'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت'),
        ),
    ]
