# Generated by Django 5.2.8 on 2025-12-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionplan_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='real_name',
            field=models.CharField(default='gold', verbose_name='نام پلن'),
            preserve_default=False,
        ),
    ]
